### ISSUE TITLE
Override service accounts per workspace/providerConfig

### ISSUE THREAD

**Issue by addisonj** [upbound/provider-terraform#150]
### What problem are you facing?

Some of my terraform, which I am looking to move to crossplane unchanged, interacts with Kubernetes and creates/manages resources.

This means I need to configure a kubernetes provider and ideally I would just use a serviceAccount.

However, it doesn't seem like I have much control over the service account used to run the terraform, with my only option being to use a `ControllerConfig` and setting `serviceAccountName` (which appears to be a deprecated API already).

While this could work, it would mean that all my terraform gets run with the same service account. Ideally, I could use different service accounts with different levels of access.

### How could Official Terraform Provider help solve your problem?

Ideally, I could have the Workspace define a service account to run as. This could be done by setting the serviceAccount on the ProviderConfig, or just on the workspace directly, though it seems like ProviderConfig would be the right place given that this is where other credentials are configured

**Comment by bobh66** [comment]
@addisonj - does the terraform kubernetes provider need to access service accounts on the local kubernetes cluster where it is running?  Or on a remote cluster?  You are correct that the ControllerConfig is the only way to set the service account that the provider-terraform pod is using, and it applies to all Workspaces in the pod, and cannot be changed at runtime.  We usually end up looking at the different auth configurations for the provider - https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#authentication  - and find the one that works the best for the desired scenario.  For example you may need to fetch a token from a service account secret and use that to configure the kubernetes provider at runtime so it has access to the resources you need.  You can also put configuration directly in the ProviderConfig, so for example you could store an entire kube config file in a secret and reference it in the ProviderConfig to make it available to the kubernetes provider inside the terraform.  An example is here - https://github.com/upbound/provider-terraform/blob/main/examples/providerconfig-terraformrc.yaml - if you replace the .terraformrc with a kubeconfig file.  Would any of those solutions work?

**Comment by addisonj** [comment]
thanks @bobh66 I think that seems reasonable... 

I think it might make sense just to give some examples, but I will close this for now.
