### ISSUE TITLE
.tf.json format support

### ISSUE THREAD

**Issue by yuriy-yarosh** [upbound/provider-terraform#165]
### What problem are you facing?

I want to use `upbound/provider-terraform` with the [`.tf.json`](https://developer.hashicorp.com/terraform/language/syntax/json) format out of [cdktf](https://developer.hashicorp.com/terraform/cdktf).

### How could Official Terraform Provider help solve your problem?

Basically, I want to be able to rename the default `main.tf` module filename [over here](https://github.com/upbound/provider-terraform/blob/main/internal/controller/workspace/workspace.go#L84), to `main.tf.json`.

So, I could pass the infline `tf.json` files as is, without relying on `go-getter` and module repo's.

**Comment by bobh66** [comment]
This seems like it would be as simple as adding the ".json" suffix to the `tfMain` constant if the Workspace `format` attribute is set to `JSON`.

That would mean the inline manifest would be expected to be in JSON format instead of YAML.

**Comment by bobh66** [comment]
Correction - we need to add `format` at the Workspace level instead of/in addition to the `varFiles` level

**Comment by yuriy-yarosh** [comment]
>  to be in JSON format instead of YAML

@bobh66 Maybe, instead of HCL ?

> instead of/in addition to the varFiles level

Nah, it has nothing to do with `varFiles` .
Only if you want to keep the existing CRD's schema the same - it's possible to impl a wacky rule "if we're passing a .tf.json -  treat it as a main.tf replacement" etc.

**Comment by bobh66** [comment]
> Maybe, instead of HCL ?

Yes, HCL - sorry.

I'd prefer to add the `format` attribute to the `Workspace`, rather than try to detect JSON vs HCL.

I'm hoping to push a PR for this in a day or two.
