### ISSUE TITLE
Terraform Provider not getting healthy

### ISSUE THREAD

**Issue by vjsahitya** [upbound/provider-terraform#168]
Hi, 
I installed up cli and uxp in my cluster. When I am trying to install upbound related provider. None of them are getting healthy. 
Not a single version of provider-terraform is getting healthy. 

While using kubectl describe providerrevisions it says: Unhealthy Package Revision

 Warning  ParsePackage       12m                 packages/providerrevision.pkg.crossplane.io  cannot initialize parser backend: failed to get uncompressed contents from layer:: TLS handshake timeout

**Comment by ytsarev** [comment]
Could you provide the exact Provider manifest you are trying to install?
Overall it looks like an environment-specific networking issue. Are you behind some form of corporate proxy?

**Comment by vjsahitya** [comment]
> Could you provide the exact Provider manifest you are trying to install? Overall it looks like an environment-specific networking issue. Are you behind some form of corporate proxy?

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.8.0


Yes I am behind corporate proxy. Will it be an issue?

**Comment by bobh66** [comment]
You will probably need to add HTTP_PROXY and HTTPS_PROXY environment variables to the crossplane helm chart deployments using the `extraEnvVarsCrossplane` map in the values.yaml so that Crossplane can pull the images for the providers.
