### ISSUE TITLE
Support for local terraform provisioner

### ISSUE THREAD

**Issue by kaushik287** [upbound/provider-terraform#190]
**What problem are you facing?**
I am using a local provisioner in my terraform scripts. Deployment of resources is happening as expected. 
_Overview::_ Deploying a EKS cluster with some network setup, and after these deployments are done, local provisioners are used to run scripts for connecting to EKS cluster and install some tools(like ArgoCD)

when local provisioners are used in scripts which are deployed by provider-terraform getting below error as it cannot identify commands (my guess)
<img width="773" alt="MicrosoftTeams-image" src="https://github.com/upbound/provider-terraform/assets/43341802/91a21ece-98e9-46ac-805f-01247e725b3a">

and on decoding message, I guess provider-terraform is not able to identify or run commands as normal terraform would do
<img width="509" alt="MicrosoftTeams-image (1)" src="https://github.com/upbound/provider-terraform/assets/43341802/4b7f29b0-5aea-4b23-a28d-e002f533df67">

**How could Official Terraform Provider community help solve your problem?**
If anyone has tried similar thing out please provide a reference example.
If terraform-provider cannot handle these cases due to some of its working limitations then please confirm

**Comment by project-administrator** [comment]
You can build a custom **provider-terraform** image, here is an example that we're using to have `psql` and `aws-cli` commands 
```
FROM xpkg.upbound.io/upbound/provider-terraform:v0.10.0
USER 0
RUN apk update && apk add postgresql-client aws-cli jq openssl procps htop dumb-init && mkdir /.aws && chown 2000 /.aws && cd /bin &&\
  curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64 &&\
  chmod +x ./aws-iam-authenticator
USER 65532
ADD .gitconfig .gitconfig
ENTRYPOINT ["dumb-init", "crossplane-terraform-provider"]
```
Then, use that custom image in your `providers.pkg.crossplane.io` `spec.package`.

**Comment by kaushik287** [comment]
Thanks for suggestions, looks like this is the best way to install required prerequisites and build image as per requirements
