### ISSUE TITLE
Support terraform v1.6

### ISSUE THREAD

**Issue by pngbai** [upbound/provider-terraform#227]
### What problem are you facing?

We are using terraform tests in our CI, it requires minimum version v1.6. https://developer.hashicorp.com/terraform/language/tests

### How could Official Terraform Provider help solve your problem?
Can you please update terraform in image to v1.6.6 (latest) please.
https://github.com/upbound/provider-terraform/blob/main/cluster/images/provider-terraform/Dockerfile#L6C20-L6C20

**Comment by jeanduplessis** [comment]
@pngbai Due to Hashicorp's switch to the BSL license, we cannot support Terraform > 1.5.5 due to incompatible license types.

**Comment by pngbai** [comment]
@jeanduplessis  ah OK, thanks for the quick feedback.

**Comment by pngbai** [comment]
@jeanduplessis can you shared please, what is your plan of the terraform update in the future ?

**Comment by jeanduplessis** [comment]
@pngbai there are no defined plans yet. We are evaluating the option of _"bring your own"_ TF CLI, or even enabling you to use OpenTofu. What we won't be able to do is ship the provider with a BSL version of TF CLI.
