### ISSUE TITLE
Introduce High Level MR metrics

### ISSUE THREAD

**Issue by andreub** [upbound/provider-terraform#271]
### What happened?

Shouldn't **High Level MR metrics** be part of the 1.16 release same as for [other official providers](https://github.com/crossplane/crossplane-runtime/pull/683)? 

### How can we reproduce it?

Not part of [1.16.0 release](https://github.com/crossplane/crossplane-runtime/releases/tag/v1.16.0) 

### What environment did it happen in?

* Crossplane Version: 1.16.0
* Provider Version: 1.16.0
* Kubernetes Version: not relevant
* Kubernetes Distribution: not relevant

**Comment by bobh66** [comment]
There is additional work required in the provider to enable metrics - see https://github.com/crossplane-contrib/provider-kubernetes/pull/224 for an example.
