### ISSUE TITLE
Support multiple terraform versions

### ISSUE THREAD

**Issue by moserke** [upbound/provider-terraform#292]
It seems like the version of terraform leveraged is pinned in the docker container.  Currently that seems to be 1.5.5 which is a year old.

1. Is there a way to leverage a newer version without having to build our own container via something like tfenv?
2. Will there be support added for selecting TF versions dynamically?

**Comment by bobh66** [comment]
Please see #282 and the references it contains.

TL;DR - no, due to BSL restrictions we cannot update to newer versions of terraform.

**Comment by jeanduplessis** [comment]
@moserke you can also read this issue which answers your questions: https://github.com/upbound/provider-terraform/issues/287
