### ISSUE TITLE
Add a way to select specific Workspaces

### ISSUE THREAD

**Issue by ltdeoliveira** [upbound/provider-terraform#39]
### What problem are you facing?

I want to:

1. As a platform engineer, handle multiple versions of Terraform on the same cluster, including offering an easy path of migration for platform users
2. As a platform engineer, I want to have multiple controller instances for each tenant in the platform, with different permissions (this is specially useful for AWS IRSA)

### How could Official Terraform Provider help solve your problem?

I'd like to select which Wokspaces a controller instance should manage based on a label selector, or something like that.

**Comment by bobh66** [comment]
@ltdeoliveira - the Workspace is cluster-scoped so we can only run a single provider instance.  Can you provide some more detail on the environment that you have Crossplane running in?  You can use different ProviderConfigs to specify different assumeRole configurations for IRSA, and you can have different Composites/Compositions for the different Terraform modules that you want to support.  I'm not sure how to restrict access to the different Composites by tenant, but I'm sure there are people with the same need.

**Comment by ltdeoliveira** [comment]
Hey @bobh66 , sorry for the late response.

So, can you elaborate a bit more on `You can use different ProviderConfigs to specify different assumeRole configurations for IRSA`. Maybe there's something I'm missing, but the IRSA annotation goes on the Provider, and this works very well for us as we don't want to deal with creating k8s secrets with AWS credentials.

Let me elaborate a bit more on how we want to use this provider. We have many teams using a common chart approach, so the platform team offers one/few common charts that the platform users can use to deploy their applications. We want to integrate the creation of cloud services that an app might need, such as Database, Cache, etc., into these charts. That's exactly what crossplane offers, but we have a huge catalog of curated Terraform modules that we want to leverage, instead of recreating everything using the provider-aws.

**Comment by bobh66** [comment]
@ltdeoliveira - the ProviderConfig spec.configuration section can contain terraform provider configuration blocks to allow assuming a specific role:

```
provider "aws" {
    region = "eu-central-1"
    assume_role {
       role_arn = "arn:aws:iam::123456789012:role/targetrole"
    }
}
```

You can use a unique ProviderConfig for each target role/account that you want to deploy to.  The downside of this is that you have to all of the provider configuration in the same block, (a limitation of terraform) so if you are deploying to different Regions you would need a ProviderConfig for each combination of the role and region.

**Comment by ltdeoliveira** [comment]
@bobh66 sorry for taking so long to try your suggestion, it does work. Since different versions of TF are already being discussed via tfenv support, I think we can close this issue.

**Comment by bobh66** [comment]
Thanks @ltdeoliveira - glad it's working.
