### ISSUE TITLE
Unable to configure the provider for multiple IRSA roles

### ISSUE THREAD

**Issue by angelbarrera92** [upbound/provider-terraform#42]
### What happened?

In the **`terraform-provider`**:

I want to use different IAM Roles (IRSA), but I'm unable to do it.
As per [docs](https://github.com/upbound/provider-terraform/blob/main/examples/aws-eks-irsa-setup.yaml), IRSA roles must be configured as an annotation in the `controllerConfig` CR.
There is no relation between `providerConfig` and `controllerConfig`, isn't it?

So I don't understand how can I enable it.

### How can we reproduce it?
Try to configure two IAM Roles (IRSA), one for team A, and another for team B.

### What environment did it happen in?

* Universal Crossplane Version:  1.10.1
* Provider Version: 0.2.0
* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`): v1.23.9
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): Vanilla
* OS (e.g. from /etc/os-release): Flatcar Container Linux by Kinvolk 3227.2.1 (Oklo)
* Kernel (e.g. `uname -a`): 5.15.58-flatcar

**Comment by angelbarrera92** [comment]
So basically, 

instead of using the 1st option: [`using-iam-roles-for-serviceaccounts`](https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#using-iam-roles-for-serviceaccounts),
I should go for the [`using-assumerolewithwebidentity`](https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#using-assumerolewithwebidentity) approach, right?

**Comment by bobh66** [comment]
Right - sorry about that, I had my providers mixed up.  As a workaround you can put the assumeRole section in the terraform provider config and patch in the account/role information that you want to assume:

```
              provider "aws" {
                region = "%s"
                assume_role {
                   role_arn = "arn:aws:iam::%s:%s"
                }
              }
```

This is based on the ControllerConfig having the appropriate assumeRole annotation:

```
eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT>:role/<ROLENAME>
```

so that the pod gets AWS credentials, and can assume the role specified in the terraform provider configuration.

Hope this helps.
