### ISSUE TITLE
Terragrunt Support

### ISSUE THREAD

**Issue by Omqarrr** [upbound/provider-terraform#43]
We see that Crossplane Terraform Provider can be used to implement GitOps methodology. We have Terraform Modules which will be invoked by Terragrunt and the way Crossplane maintains the state of infrastructure created by Terraform, in the same way can it support the infrastructure created by Terragrunt?

If no, Is there any plan in near future to support this?

**Comment by bobh66** [comment]
@Omqarrr can you elaborate on this scenario?  What functionality are you looking for from provider-terraform?  Would it need to execute a terragrunt CLI in place of the terraform CLI?  It would be helpful to have some detail on what the use case is and what the expected behavior of the provider would be.   Thanks!

**Comment by Omqarrr** [comment]
@bobh66 thanks for the quick reply. 

Yes, your understanding is correct. We will be executing Terragrunt commands that will require Terragrunt CLI.

**Comment by ytsarev** [comment]
@Omqarrr could you describe what kind of advantages it will bring to this provider?

**Comment by Omqarrr** [comment]
@ytsarev listing down the advantages below:

- Terragrunt promotes DRY behavior. **DRY** - **D**ont **R**epeat **Y**ourself 
- Terraform Configuration Files need not be modified each and every time. This can be achieved with Terragrunt. Pass the values with help of Terragrunt without modifying Terraform code
- Managing state file for every environment with Terraform, same code will be required to be duplicated in each folder structure. But with Terragrunt, a common piece of code can be pulled in different folders / per environment.
- Terraform CLI can be kept DRY by features from Terragrunt with extra_arguments.
- Additional feature to run custom code before or after running Terraform

Some more advantages: https://terragrunt.gruntwork.io/docs/#features

**Comment by bobh66** [comment]
@Omqarrr - thanks.  Can you provide a sample of what a terragrunt "workspace" might look like?  I'm wondering if this is better implemented as a separate provider, or as a separate resource under the existing provider.   It would be helpful to understand what the experience would look like for the user (what does the Managed Resource spec look like) and what needs to happen inside the provider to implement the spec.

**Comment by Omqarrr** [comment]
@bobh66 @ytsarev. sure, thanks.

We have a sample setup that involves Terraform Modules which are invoked by Terragrunt.

**Terraform Modules** are maintained in: https://github.com/Omqarrr/aws-vpc-network-terraform.git
----------------------------------------------------------------------------------------------------------------

**Terragrunt Scripts** are maintained in: https://github.com/Omqarrr/terragrunt-multi-env-management.git
-----------------------------------------------------------------------------------------------------------------------

**Usage**
-----------
- Terraform Modules/ Repo will not be modified for managing the infrastructure in different environments.
- Different Environments are managed by Terragrunt with **dev/staging/prod** folder structure.
- To create infrastructure in dev region, move to `environment/dev/` and run `terragrunt apply`
- `s3-backend.tf` file is generated by Terragrunt as configured in `terragrunt.hcl` present in `root`

**Note**
----------
- terragrunt.hcl in the root defines what the children should inherit.

**Comment by ronaldmiranda** [comment]
i'm interested to help! looks promising!

**Comment by vjda** [comment]
Hey guys!!! any news on this?, it would be awesome to be able to use Terragrunt with Crossplane 🚀.

Is anyone working on this?, I don't have much experience in Go, but I think I could eventually help move forward with this if that helps!

**Comment by bobh66** [comment]
Hi @vjda - there is no work happening on this that we know of.  I think it would be a good idea to have a one-pager design document that describes what the API would look like and how it fits with the existing provider, as discussed in this comment: https://github.com/upbound/provider-terraform/issues/43#issuecomment-1362934272

**Comment by DiegoLelis** [comment]
Also highly interested on this!

**Comment by bobh66** [comment]
Please see #287 for the official position on this issue.
