### ISSUE TITLE
Expose more context around errors 

### ISSUE THREAD

**Issue by ytsarev** [upbound/provider-terraform#54]
### What problem are you facing?

See https://github.com/crossplane-contrib/provider-terraform/issues/24 and https://github.com/crossplane-contrib/provider-terraform/issues/61 in the old repo

Currently, we are frequently missing the context in the errors exposed in the event stream and it seriously complicates the debugging; see recent example [in slack](https://crossplane.slack.com/archives/C01TRKD4623/p1672839754095039)

### How could Official Terraform Provider help solve your problem?

Find a way to provide more context. It can take different/multiple forms:

* More verbose Event messages with context included
* Writing the log somewhere in the pod and exposing and documenting clear guidance on where to find it
* Find more consistent way to expose the logs, see https://github.com/crossplane-contrib/provider-terraform/issues/61

**Comment by mbbush** [comment]
Is this fully resolved by #124?

**Comment by bobh66** [comment]
This is probably a duplicate of #37 - @ytsarev , ok to close as a dup?

**Comment by ytsarev** [comment]
Totally, thanks for the catch.
