### ISSUE TITLE
Allow IRSA Role IDs to be Specified on the `ProviderConfig`

### ISSUE THREAD

**Issue by chr0n1x** [upbound/provider-terraform#70]
### What problem are you facing?

I see that in [the IRSA example](https://github.com/upbound/provider-terraform/blob/main/examples/aws-eks-irsa-setup.yaml#L30-L31) the `eks.amazonaws.com/role-arn` annotation is used. But this is on the controller config. Is there a way to specify this argument to the provider on the `ProviderConfig`?

i.e. given a single cluster w/ `namespace1` and `namespace2`, xplane & the TF provider installed:

- `namespace1` has it's own `ProviderConfig` with IRSA set up between the cluster that's running xplane and `aws-account-1`
- `namespace2` has a different `ProviderConfig` also with IRSA set up. But it's provider config specifies an ARN for STS AssumeRole to `aws-account-2`

The reason why the barebones approach in the linked example is a problem is that it does not scale well when there are multiple AWS accounts that need to be synced to across multiple projects/namespaces.

### How could Official Terraform Provider help solve your problem?

I know that `ProviderConfig`s are cluster-wide so maybe Im barking up the wrong tree. But either way, is there a way to inject this at the provider config level instead? Or are there any plans to support this? I believe that having `role-arn` be configurable at the `ProviderConfig` level (instead of the `ControllerConfig` level) would allow cluster operators that manage multi tenant/cluster setups the ability to provide an installation of the TF Xplane provider as a service.

**Comment by bobh66** [comment]
@chr0n1x IRSA controls the AWS credentials that are made available to the pod/container via environment variables and volume mounts, so they can only be configured container-wide via ControllerConfig.   The typical use case is to have the ControllerConfig specify an account/role for the provider-terraform pod/container to run under by default, and then use the assume_role {role_arn= <roleARN>} in the provider configuration to switch to the account/role that the resources need to be applied to.   This can be done either via patching to an Inline workspace or in a ProviderConfig, though terraform does not merge provider configurations so you would need to specify the entire provider configuration block - including Region - in the same ProviderConfig configuration section.   Then of course you need to configure all of the ProviderConfig specified roles to be assumable by the IRSA role that the provider is running as.  So you would have a ProviderConfig per role/region that you want to deploy into.

**Comment by bobh66** [comment]
@chr0n1x - is it ok to close this issue?  Thanks
